### ISSUE TITLE
Does this work with Sony UBP-X700?

### ISSUE THREAD

**Issue by typhoon2099** [Drafteed/pybravia#5]
Does this library work with the Sony UBP-X700? It should as far as I'm aware, but I've just done a quick test to try it out and hit the following error:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1064, in create
_connection
    raise exceptions[0]
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1049, in create
_connection
    sock = await self._connect_sock(
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 960, in _connec
t_sock
    await self.sock_connect(sock, address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 500, in soc
k_connect
    return await fut
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 535, in _so
ck_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('192.168.1.38', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/matthewsimpson/Projects/Drafteed/pybravia/pybravia/client.py", line 154, in send_req
    response = await self._session.post(
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/opt/homebrew/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.38:80 ssl:default [Connect call failed ('192.168.1.38', 80)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/matthewsimpson/Projects/Drafteed/pybravia/playground.py", line 7, in test
    await client.pair("CLIENTID", "NICKNAME")
  File "/Users/matthewsimpson/Projects/Drafteed/pybravia/pybravia/client.py", line 105, in pair
    await self.register(PAIR_PIN, clientid, nickname)
  File "/Users/matthewsimpson/Projects/Drafteed/pybravia/pybravia/client.py", line 95, in register
    await self.send_rest_req(
  File "/Users/matthewsimpson/Projects/Drafteed/pybravia/pybravia/client.py", line 235, in send_rest_req
    return await self.send_req(
  File "/Users/matthewsimpson/Projects/Drafteed/pybravia/pybravia/client.py", line 173, in send_req
    raise BraviaTVConnectionError from err
pybravia.exceptions.BraviaTVConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matthewsimpson/Projects/Drafteed/pybravia/playground.py", line 11, in <module>
    asyncio.run(test())
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_unt
il_complete
    return future.result()
  File "/Users/matthewsimpson/Projects/Drafteed/pybravia/playground.py", line 8, in test
    except BraviaTVError:
NameError: name 'BraviaTVError' is not defined

shell returned 1
```

I've tried to [connect in the past](https://github.com/typhoon2099/sony-device-control) and managed to connect and control it, but I've never been able to package it up and make use of it (aka add it to Home Assistant). My reason for bringing this up is that it should be possible to expand the scope of this library beyond just Bravia TVs and include other devices which can be controlled via IRCC.

EDIT: Also worth noting, the repo I linked to above contains some code related to discovering Sony devices on your network. I'm not sure how Home Assistant is set up for UPNP discovery, but there should at least be some information in there that could be applied to Home Assistant to enable autodiscovery for Sony IRCC devices.

**Comment by Drafteed** [comment]
> My reason for bringing this up is that it should be possible to expand the scope of this library beyond just Bravia TVs and include other devices which can be controlled via IRCC.

I'm not sure if this is possible. Bravia TVs use IRCC to send remote commands only. All other interaction with the device (auth, get status, select source, etc.) is carried out through the [Bravia REST API](https://pro-bravia.sony.net/develop/integrate/rest-api/spec/index.html). Unfortunately, the Sony APIs differ for different types of devices. For example, [Sony Songpal](https://www.home-assistant.io/integrations/songpal/) devices use a [similar API](https://developer.sony.com/develop/audio-control-api/documentation/api-reference), but it differs in many aspects, at least in that it can implement a push connection through sockets. Supporting different APIs in one library would probably be a difficult task. 

Also, I couldn't find official API documentation for Blu-ray players. Try out https://github.com/rytilahti/python-songpal maybe your device supports the Audio Control API.

**Comment by typhoon2099** [comment]
It should be possible, the UBP-X700 supports IRCC (it has a remote control after all):

```
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
    <deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
    <friendlyName>UBP-X700</friendlyName>
    <manufacturer>Sony Corporation</manufacturer>
    <manufacturerURL>http://www.sony.net/</manufacturerURL>
    <modelDescription></modelDescription>
    <modelName>Blu-ray Disc Player</modelName>
    <modelURL></modelURL>
    <UDN>uuid:00000003-0000-1010-8000-44e4ee04d418</UDN>
    <iconList>
      <icon>
        <mimetype>image/jpeg</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>24</depth>
        <url>/bdp_ce_device_icon_large.jpg</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>24</depth>
        <url>/bdp_ce_device_icon_large.png</url>
      </icon>
      <icon>
        <mimetype>image/jpeg</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/bdp_ce_device_icon_small.jpg</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/bdp_ce_device_icon_small.png</url>
      </icon>
    </iconList>
    <serviceList>
      <service>
        <serviceType>urn:schemas-sony-com:service:IRCC:1</serviceType>
        <serviceId>urn:schemas-sony-com:serviceId:IRCC</serviceId>
        <SCPDURL>/IRCCSCPD.xml</SCPDURL>
        <controlURL>/upnp/control/IRCC</controlURL>
        <eventSubURL></eventSubURL>
      </service>
    </serviceList>
    <presentationURL></presentationURL>
    <av:X_IRCC_DeviceInfo xmlns:av="urn:schemas-sony-com:av">
      <av:X_IRCC_Version>1.0</av:X_IRCC_Version>
      <av:X_IRCC_CategoryList>
        <av:X_IRCC_Category>
          <av:X_CategoryInfo>AAMAABxa</av:X_CategoryInfo>
        </av:X_IRCC_Category>
      </av:X_IRCC_CategoryList>
    </av:X_IRCC_DeviceInfo>
    <av:X_UNR_DeviceInfo xmlns:av="urn:schemas-sony-com:av">
      <av:X_UNR_Version>1.3</av:X_UNR_Version>
      <av:X_CERS_ActionList_URL>http://192.168.1.138:50002/actionList</av:X_CERS_ActionList_URL>
    </av:X_UNR_DeviceInfo>
    <av:X_RDIS_DeviceInfo xmlns:av="urn:schemas-sony-com:av">
      <av:X_RDIS_Version>1.0</av:X_RDIS_Version>
      <av:X_RDIS_SESSION_CONTROL>false</av:X_RDIS_SESSION_CONTROL>
      <av:X_RDIS_ENTRY_PORT>50004</av:X_RDIS_ENTRY_PORT>
    </av:X_RDIS_DeviceInfo>
  </device>
</root>

```

**Comment by typhoon2099** [comment]
Hmm, I've done a bit more digging around this morning and it does indeed look like it's a completely different registration process for the UBP-X700. I think this was the reason I started trying to code it up myself, because I couldn't find another library that handled it. I'll keep working on my own repo for now, and if I can find a way to make the registration process composable/discoverable then I'll try and get a PR up.
